version: "3.8"

networks:
  web-network:
  server-network:

services:
  # Web Server
  server:
    build:
      context: ./
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile.dev
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app/
      - /app/web
    networks:
      - server-network
    environment:
      PORT: 4000

  # Web
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./web:/app
      - /app/node_modules/.
    networks:
      - web-network
    environment:
      PORT: 3000

  # Ingress
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    networks:
        - web-network
        - server-network
    ports:
      - 8080:8080
