FROM node:18.12.0

RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

WORKDIR /app

COPY . .

RUN pnpm install

# Ensure eslint does not run
ENV DISABLE_ESLINT_PLUGIN=true


CMD ["pnpm", "dev"]
